### ISSUE TITLE
ARM GPU or Android support

### ISSUE THREAD

**Issue by kindloaf** [benoitsteiner/tensorflow-opencl#63]
Hi, from the documentation I saw that the OpenCL support is on Linux only, and I saw that it's mainly tested on AMD GPUs. I'm wondering how much effort will be needed to support (1) ARM GPU such as the Mali series (2) Running tensorflow-opencl on Android?

**Comment by c00lrain** [comment]
It's not tried yet but officially Google not allowed running openCL on Android. However till Android MM could using openCL using NDK build with openCL stub library. Unfortunately Android N enhanced security feature then audit name space and classified external library from bionic C lib. Thus openCL verifying and benchmark Android Apk on the Google store can not be run. But this is result from my environment not globally tested. In case of ARM MALI, as default openCL enabled in common GPU API library because ARM MALI use openCL as back-end of RenderScriptCompute. Otherwise, other mobile GPU from Imagination & Qualcomm provide native acceleration for RenderScriptCompute so, openCL API runtime and compiler not included on Driver kit for Android. Long time ago, Google ignore, Qualcomm inject openCL library of Adreno  to Nexus series, but now Nexus not contain these runtime 
 & compilers.

**Comment by kindloaf** [comment]
@c00lrain Thanks for the info! The situation looks pretty complicated.

**Comment by laMia482** [comment]
@c00lrain  Thanks for the info! But have it succeeded in running tensorflow on a MALI-GPU-equipped Android device with the GPU enabled?
